# Generated by Django 5.0 on 2024-01-07 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicsReviewApp', '0002_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=datetime.datetime(2024, 1, 7, 21, 48, 25, 896009, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 21, 48, 43, 637158, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
